### ISSUE TITLE
Problem installing through npm as of 1.2.0

### ISSUE THREAD

**Issue by avikj** [matheuss/hpm#17]
After installing hpm through `sudo npm install -g hpm-cli` and running `hpm` I got the following error:
```sh
module.js:442
    throw err;
    ^
Error: Cannot find module './api'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/hpm-cli/index.js:17:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```
I checked the install directory and it doesnt't have api.js in it, and it doesn't seem to be there on [npmcdn](https://npmcdn.com/hpm-cli@1.2.0/) either.

**Comment by matheuss** [comment]
Thanks for noticing this man! I forgot to rename things in `package.json`. (`hyperterm.js` => `api.js`).
