### ISSUE TITLE
Syntax error: use of const in strict mode

### ISSUE THREAD

**Issue by nehero** [matheuss/hpm#22]
Fresh install of hpm, getting this error. Could open a PR to fix if I have time later today.

```
/usr/local/lib/node_modules/hpm-cli/index.js:3
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by matheuss** [comment]
Which Node.js version are you using?
![screen shot 2016-08-02 at 1 57 51 pm](https://cloud.githubusercontent.com/assets/4721750/17337456/168a2cb6-58b9-11e6-9894-7584c0976f25.png)

**Comment by nehero** [comment]
Hah. That's embarrassing. I was on my work laptop and I guess I haven't used node in a while 😆  I was on `v 0.12`. 

Updated to current stable and we're all good 👍  Thanks!
